
export const GET_COMMENTS_REQUEST = 'commentList/GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'commentList/GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED = 'commentList/GET_COMMENTS_FAILED';

export const SEND_COMMENT_REQUEST = 'commentForm/SEND_COMMENT_REQUEST';
export const SEND_COMMENT_SUCCESS = 'commentForm/SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAILED  = 'commentForm/SEND_COMMENT_FAILED';
