
export const GET_CATEGORIES_REQUEST = "postForm/GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "postForm/GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "postForm/GET_CATEGORIES_FAILED";

export const SAVE_POST_REQUEST = "postForm/SAVE_POST_REQUEST";
export const SAVE_POST_SUCCESS = "postForm/SAVE_POST_SUCCESS";
export const SAVE_POST_FAILED = "postForm/SAVE_POST_FAILED";

export const RESET_FORM_STATE = "postForm/RESET_FORM_STATE";
